# Macro Economics Indicators

**Autor:** Frederick Salazar Sanchez <br>
**Date:** March of 2025 <br>
**Description:** This notebook

In [48]:
import pandas as pd

In [49]:
df_pib = pd.read_csv('./data/in/countries_gdp_hist.csv',sep=';')

In [50]:
df_pib_per_capita = pd.read_csv('./data/in/pib_per_capita_countries_dataset.csv', sep=',')\
                      .drop(columns=['country_name',
                                     'region',
                                     'sub_region',
                                     'intermediate_region',
                                     'indicator_code',
                                     'indicator_name'])\
                      .rename(columns={'country_code':'country_code_percapita',
                                       'year':'year_percapita',
                                       'gdp_variation':'gdp_variation_percapita'})

In [51]:
df_exports = pd.read_csv('./data/in/export_goods_services_countries_dataset.csv', sep=',')\
                .drop(columns=['country_name',
                               'region',
                               'sub_region',
                               'intermediate_region',
                               'indicator_code',
                               'indicator_name'])\
                .rename(columns={'country_code':'country_code_exports',
                                 'year':'year_exports'})

In [52]:
df_inflation = pd.read_csv('./data/in/global_inflation_countries.csv', sep=',')\
                .drop(columns=['country_name',
                               'region',
                               'sub_region',
                               'intermediate_region',
                               'indicator_code',
                               'indicator_name'])\
                .rename(columns={'country_code':'country_code_inflation',
                                 'year':'year_inflation'})

In [53]:
df_imports = pd.read_csv('./data/in/import_goods_services_countries_dataset.csv', sep=',')\
                .drop(columns=['country_name',
                               'region',
                               'sub_region',
                               'intermediate_region',
                               'indicator_code',
                               'indicator_name'])\
                .rename(columns={'country_code':'country_code_imports',
                                 'year':'year_imports'})

# Creation a unique dataframe with all data

In [54]:
df_economics = pd.merge(df_pib, df_pib_per_capita,
                        left_on=['country_code', 'year'],
                        right_on=['country_code_percapita', 'year_percapita'],
                        how='left')\
                .merge(df_exports,
                       left_on=['country_code', 'year'],
                       right_on=['country_code_exports', 'year_exports'],
                       how='left')\
                .merge(df_imports,
                       left_on=['country_code', 'year'],
                       right_on=['country_code_imports', 'year_imports'],
                       how='left')\
                .merge(df_inflation,
                       left_on=['country_code', 'year'],
                       right_on=['country_code_inflation', 'year_inflation'],
                       how='left')\
                .drop(columns=['country_code_percapita',
                               'year_percapita',
                               'country_code_exports',
                               'year_exports',
                               'country_code_inflation',
                               'year_inflation',
                               'country_code_imports',
                               'year_imports'])

In [55]:
df_economics

,country_code,region_name,sub_region_name,intermediate_region,country_name,income_group,year,total_gdp,total_gdp_million,gdp_variation,gdp_per_capita,gdp_variation_percapita,exports_of_goods_and_services,imports_of_goods_and_services,inflation_rate
0,ABW,AMERICAS,LATIN AMERICA AND THE CARIBBEAN,CARIBBEAN,ARUBA,INGRESO ALTO,1960,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,ABW,AMERICAS,LATIN AMERICA AND THE CARIBBEAN,CARIBBEAN,ARUBA,INGRESO ALTO,1961,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,ABW,AMERICAS,LATIN AMERICA AND THE CARIBBEAN,CARIBBEAN,ARUBA,INGRESO ALTO,1962,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,ABW,AMERICAS,LATIN AMERICA AND THE CARIBBEAN,CARIBBEAN,ARUBA,INGRESO ALTO,1963,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,ABW,AMERICAS,LATIN AMERICA AND THE CARIBBEAN,CARIBBEAN,ARUBA,INGRESO ALTO,1964,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13755,ZWE,AFRICA,SUB-SAHARAN AFRICA,EASTERN AFRICA,ZIMBABWE,PAÍSES DE INGRESO MEDIANO BAJO,2019,2.571741e+10,25717.409842,-6.332446,1684.027904,-7.785580,27.554156,28.241805,255.304991
13756,ZWE,AFRICA,SUB-SAHARAN AFRICA,EASTERN AFRICA,ZIMBABWE,PAÍSES DE INGRESO MEDIANO BAJO,2020,2.686794e+10,26867.936445,-7.816951,1730.413489,-9.333971,22.293063,25.020302,557.201817
13757,ZWE,AFRICA,SUB-SAHARAN AFRICA,EASTERN AFRICA,ZIMBABWE,PAÍSES DE INGRESO MEDIANO BAJO,2021,2.724052e+10,27240.515109,8.468017,1724.387731,6.611911,22.775241,28.071888,98.546105
13758,ZWE,AFRICA,SUB-SAHARAN AFRICA,EASTERN AFRICA,ZIMBABWE,PAÍSES DE INGRESO MEDIANO BAJO,2022,3.278975e+10,32789.751736,6.139263,2040.552459,4.343667,27.872171,36.891437,104.705171
13759,ZWE,AFRICA,SUB-SAHARAN AFRICA,EASTERN AFRICA,ZIMBABWE,PAÍSES DE INGRESO MEDIANO BAJO,2023,3.523137e+10,35231.367886,5.336730,2156.034004,NaN,21.579400,29.215564,0.000000

# save Proccessed File to csv

In [57]:
df_economics.to_csv('./data/out/macro_economics_indicators.csv', index=False)